all: thumbs/pic1.jpg thumbs/pic2.jpg thumbs/pic3.jpg
	
thumbs/pic1.jpg: pictures/pic1.jpg
	convert -thumbnail 100 $< $@

thumbs/pic2.jpg: pictures/pic2.jpg
	convert -thumbnail 100 $< $@
thumbs/pic3.jpg: pictures/pic3.jpg
	
	convert -thumbnail 100 $< $@
